### ISSUE TITLE
set_time_limit() no longer supported in IPS v6.0

### ISSUE THREAD

**Issue by Brovning** [brownson/IPSLibrary#25]
![image](https://user-images.githubusercontent.com/39644775/129471230-e7fb7178-0619-44a0-b224-25e19e146198.png)

**Comment by brownson** [comment]
Hi,

die Library verwendet den Development Branch und dort ist das Problem bereits behoben:
https://github.com/brownson/IPSLibrary/blob/Development/IPSLibrary/install/IPSModuleManager/IPSModuleManager.class.php

**Comment by Brovning** [comment]
Ok, aber vielleicht wäre meine Lösung trotzdem die bessere, um die Abwärtskompatibilität für bspw. Leute ohne Subscription zu gewährleisten.

```
if(IPS_GetKernelVersion() < 6)
    set_time_limit($timeLimit);
```

**Comment by brownson** [comment]
ja, durchaus, kann das bei nächster Gelegenheit mal nachziehen oder Du schickst mir am Development Branch einen Pull Request.
